### ISSUE TITLE
Infinite loop on Windows

### ISSUE THREAD

**Issue by twisted-nematic57** [gmarino2048/64bit-os-tutorial#4]
I installed Cygwin and everything for the `cp` and `cat` commands, and did everything like in the tutorial. But QEMU is showing an infinite loop.

Is it possible that you could port this tutorial over to Windows through Batchfile please? Thanks.

**Comment by gmarino2048** [comment]
Hello, Windows support is not something I'm willing to work for at this time. Since Microsoft has chosen to not support separate shells without emulation, I'd have to write and test Windows versions for all of the build scripts. I'm busy working on other projects at this time, and don't have time right now to put in the work it would take to ensure the same level of quality on Windows.

The other reason that I probably won't end up catering to Windows for this project is because Linux is [completely free](https://ubuntu.com/download/desktop) to use. Not only is the software itself free, but you can also run a Virtual Machine for free using [VirtualBox](https://www.virtualbox.org/). This is the route I would recommend for Windows users, as the virtual machine is very lightweight and should run on most devices. To be honest, support for Mac was more of a happy accident since the commands just happened to work with minimal effort. Ubuntu 20.04 will always be the recommended development environment for this project.

That being said, QEMU should be platform agnostic, and the behavior of the provided files should not change just because you're running on WIndows. The scripts themselves use infinite loops to "terminate" the program once they've finished, so please verify that the behavior is actually unexpected. This also sounds like it could be an issue with QEMU, although with the very limited information I have here it's impossible to tell. If you end up working through the issue, feel free to submit a pull request, and I'll see if I can take a look through it.

**Comment by twisted-nematic57** [comment]
Hi, I just ended up literally copypasting everything again and now it works. I must've mis-typed something.
Thanks again for being a champ and making this whole thing 💖
