### ISSUE TITLE
Chapter 2.2: Infinite boot loop

### ISSUE THREAD

**Issue by twisted-nematic57** [gmarino2048/64bit-os-tutorial#6]
Ok, this one actually isn't my fault. I set up a full-fledged 64-bit Linux VM and installed all the dependencies for building. But QEMU is again, showing an infinite boot loop. First I thought that I did something horribly wrong, so I replaced my source files with the ones provided in chapter 2.2 - Still no avail! It seems that the issue in chapter 2.2 breaks every single chapter ahead of that.

Everything works just fine up until chapter 2.1 by the way.

**Comment by gmarino2048** [comment]
Hi @HackerDaGreat57, I am unable to reproduce this issue, and since I don't have anything to go on besides "infinite loop" I'm afraid there's nothing I can do to help you. The code for the bootloader in Chapter 2.2 is identical to earlier chapters, so you may want to try using the debugger script to figure out what is going wrong.

In the future, I will need more detailed information about the issue in order to help fix it. The only supported use case is when the files are in the repository on the latest version of the master branch. If you are moving files around or copying their contents elsewhere, then it is your responsibility to ensure that these files work with your environment. To validate the chapter as it was originally written, you can run `$ git fetch; git reset --hard origin/master` followed by `git clean -fdx`. If the problem persists, you may have other issues with QEMU which I will not be able to solve.

**Comment by gmarino2048** [comment]
Duplicates #4
