### ISSUE TITLE
Will this project continue?

### ISSUE THREAD

**Issue by ghost** [gmarino2048/64bit-os-tutorial#7]
Hi, This project of your's really helped me understand operating systems. But I would like it even more if it was continued. 

So is this project being continued?

If not, is there any active os-tutorials?

**Comment by twisted-nematic57** [comment]
I have the same question too. A few months ago I asked if they were going to do GUI tutorials @gmarino2048 said that it wasn't in the scope of this tutorial.

**Comment by gmarino2048** [comment]
Hi everyone, I'm still planning on continuing this tutorial, but I'm currently finishing my MS degree and so that takes priority for the time being. While I don't plan on adding new content until I'm done with school, I'm happy to fix anything that's wrong with the current tutorial. So if you find any bugs, please submit an issue for them.

To add to the comment about GUI tutorials, the reason I don't have anything planned at the moment is because operating the graphics card and a multiple window desktop environment relies on many components that I haven't even started implementing yet (Filesystems, SATA devices, PCIe devices, USB devices, SMP, and graphics drivers to name a few). There are a lot of complex components involved in even the most basic GUI, so it would take me a ton of time and effort to even get that far.

I don't want it to seem like I'm not interested in getting there eventually, but I have other things I need to do at the moment. If you'd be interested in contributing, please feel free to reach out.

**Comment by twisted-nematic57** [comment]
I understand your concerns (I'm in 8th grade, you know 😉). Take your time, no problem. We understand. 👍

**Comment by GrooverMD** [comment]
Hi gmarino2048,

I am looking foward to more tutorials when your time permits., great work by the way.
